### ISSUE TITLE
Trouble syncing across devices

### ISSUE THREAD

**Issue by kevqadir777** [ankidroid/ankidroiddocs#40]
Traceback (most recent call last):
  File "aqt\webview.py", line 152, in _linkHandler
  File "aqt\toolbar.py", line 74, in _linkHandler
  File "aqt\toolbar.py", line 97, in _syncLinkHandler
  File "aqt\main.py", line 589, in onSync
  File "aqt\main.py", line 319, in unloadCollection
  File "anki\collection.py", line 155, in close
  File "anki\db.py", line 43, in execute
sqlite3.OperationalError: database is locked

**Comment by nicolas-raoul** [comment]
This issue tracker is for problems with the AnkiDroid documentation.
For Anki Desktop problems see https://anki.tenderapp.com
Thanks for using Anki! :-)
